# Generated by Django 4.2 on 2025-05-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='SiteObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('documentation_type', models.IntegerField(choices=[(1, 'КЖ'), (2, 'КМ'), (3, 'АР')], default=1, verbose_name='Вид документации')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Объем')),
                ('file_name', models.CharField(max_length=200, verbose_name='Название файла')),
                ('inventory_number', models.CharField(max_length=20, verbose_name='Инвентарный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlimportapp.customer', verbose_name='Заказчик')),
                ('site_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlimportapp.siteobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-created_at'],
            },
        ),
    ]
