# Generated by Django 4.2 on 2025-05-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlimportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='Хэш файла'),
        ),
    ]
